# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#thanks to cat for helping slurp this stuff
karkat = '{\"lastPlayed\":\"1542840462569\",\"isempress\":\"false\",\"hatchDate\":\"1542840462569\",\"lastFed\":\"1542840462569\",\"dollDATAURL\":\"Karkat Vantas:___HBRpaWn_AADuAABpaWmZmZmJiYn_uin_uikAAAAAAABLS0s6OjoREREAAAAREREzMzPExMT_AAB_AAAIgrBWN_4eDwWC2A==\",\"boredomJson\":\"0\",\"nameJSON\":\"Karkat Vantas\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"0\",\"curious\":\"0\",\"loyal\":\"113\",\"energetic\":\"0\",\"external\":\"0\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
feferi = '{\"lastPlayed\":\"1542843765974\",\"isempress\":\"false\",\"hatchDate\":\"1542843765974\",\"lastFed\":\"1542843765974\",\"dollDATAURL\":\" Feferi Peixes:___HBSZAE2xEmL_qeUA-lEEsj7_qeX_uin_uimZAE0AAAAA3v43qskREREuLi6xEmKZAE3ExMSZAE13ACsIgsBYOgqEBQKcJhQKAkBJgA==\",\"boredomJson\":\"0\",\"nameJSON\":\" Feferi Peixes\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"0\",\"curious\":\"0\",\"loyal\":\"0\",\"energetic\":\"113\",\"external\":\"0\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
terezi = '{\"lastPlayed\":\"1542843765974\",\"isempress\":\"false\",\"hatchDate\":\"1542843765974\",\"lastFed\":\"1542843765974\",\"dollDATAURL\":\"Terezi Pyrope:___YU8QAAAIKCAGBgAIKCAGBgAEBA8QAA8QAAAIKCAAAAAAAASkpKERERSkpK8QAApAYIxMTEAIKCAGBgCILwXgmFg-_ASQsWAogFFg",\"boredomJson\":\"0\",\"nameJSON\":\" Terezi Pyrope\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"0\",\"curious\":\"0\",\"loyal\":\"0\",\"energetic\":\"0\",\"external\":\"113\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
sollux = '{\"lastPlayed\":\"1542840462569\",\"isempress\":\"false\",\"hatchDate\":\"1542840462569\",\"lastFed\":\"1542840462569\",\"dollDATAURL\":\"Sollux+Captor%3A___HBShoQChoQCAgAChoQCAgABgYADyAAAAO_-hoQAAAABTU1MuLi4REREuLi7___8uLi7ExMShoQBQUAAIgtBaCWL_O2CIEWA%3D\",\"boredomJson\":\"0\",\"nameJSON\":\"Sollux Captor\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"0\",\"curious\":\"0\",\"loyal\":\"0\",\"energetic\":\"-113\",\"external\":\"0\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
vriska = '{\"lastPlayed\":\"1542840462569\",\"isempress\":\"false\",\"hatchDate\":\"1542840462569\",\"lastFed\":\"1542840462569\",\"dollDATAURL\":\"Vriska+Serket%3A___HBQAQYIAQYIAIGAnJycAIGBDQ0P_uin_uikAQYIAAAAAFCkAQYIRERFKSkruAAAAAADExMQAQYIAIEEIgxBiLjP48eHA5g%3D%3D\",\"boredomJson\":\"0\",\"nameJSON\":\"Vriska Serket\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"0\",\"curious\":\"113\",\"loyal\":\"0\",\"energetic\":\"0\",\"external\":\"0\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
kanaya = '{\"lastPlayed\":\"1542840462569\",\"isempress\":\"false\",\"hatchDate\":\"1542840462569\",\"lastFed\":\"1542840462569\",\"dollDATAURL\":\"Kanaya+Maryam%3A___HBRN4loHhEYDQiPyAACqAABKSkr_uin_uikHhEYAAADyAACqAAARERFKSkrExMQAAADExMQHhEYDQiMIgqBUCP_MCgFAbDeA\",\"boredomJson\":\"0\",\"nameJSON\":\"Kanaya Maryam\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"113\",\"idealistic\":\"0\",\"curious\":\"0\",\"loyal\":\"0\",\"energetic\":\"0\",\"external\":\"0\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
tavros = '{\"lastPlayed\":\"1542840462569\",\"isempress\":\"false\",\"hatchDate\":\"1542840462569\",\"lastFed\":\"1542840462569\",\"dollDATAURL\":\"Tavros+Nitram%3A___HBSiUgOiUgNRKQEAAADzewJJSUn_uin_uimiUgMAAAAAAABJSUkRERFJSUmiUgNjMgLExMSiUgNRKQEIgQgIQFSBl_MAkwEmHQ7g\",\"boredomJson\":\"0\",\"nameJSON\":\"Tavros Nitram\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"0\",\"curious\":\"0\",\"loyal\":\"-113\",\"energetic\":\"0\",\"external\":\"0\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
eridan = '{\"lastPlayed\":\"1542840462569\",\"isempress\":\"false\",\"hatchDate\":\"1542840462569\",\"lastFed\":\"1542840462569\",\"dollDATAURL\":\"Eridan+Ampora%3A___HBT_mTNqAGoTLWlqAGqQAJBFAEX_uin_uilqAGoAAAAAAAAGFTYAAAAuLi4CbJEEM2zExMRhAGEwADAIgnBOBkgVhwUCnIc4UCmA\",\"boredomJson\":\"0\",\"nameJSON\":\"Eridan Ampora\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"113\",\"curious\":\"0\",\"loyal\":\"0\",\"energetic\":\"0\",\"external\":\"0\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
gamzee = '{\"lastPlayed\":\"1542840462569\",\"isempress\":\"false\",\"hatchDate\":\"1542840462569\",\"lastFed\":\"1542840462569\",\"dollDATAURL\":\"Gamzee+Makara%3A___HBRjHbRjHbRBC5Lk5ORBC5J8fHz_uin_uiljHbQAAAAAAAAhISERERFKSkpjHbQ3A23ExMRjHbQxDloIgpBSJ_grYKgVB4PY\",\"boredomJson\":\"0\",\"nameJSON\":\"Gamzee Makara\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"-113\",\"curious\":\"0\",\"loyal\":\"0\",\"energetic\":\"0\",\"external\":\"0\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'
nepeta = '{\"lastPlayed\":\"1542840462569\",\"isempress\":\"false\",\"hatchDate\":\"1542840462569\",\"lastFed\":\"1542840462569\",\"dollDATAURL\":\"Nepeta+Leijon%3A___HBRBZgBBZgAgRABBZgAgRAAAIgD_uin_uilBZgAAAABLS0s6OjoREREAAAAAO_8AHoLExMRBZgAgMwAIgsBYv8ogQFwvgA%3D%3D\",\"boredomJson\":\"0\",\"nameJSON\":\"Nepeta+Leijon\",\"healthJson\":\"100\",\"TYPE\":\"GRUB\",\"corrupt\":\"false\",\"purified\":\"false\",\"patience\":\"0\",\"idealistic\":\"0\",\"curious\":\"0\",\"loyal\":\"0\",\"energetic\":\"0\",\"external\":\"-113\",\"remembered\":\"{}\",\"rememberedNames\":\"{}\",\"rememberedCastes\":\"{}\"}","breeder":"ParadoxSpace"}'



permanents = [karkat,feferi,terezi]

#TimeHole.create(permanent: true , wigglerJSON: '')

#keeps it from remaking seeds already in the system
permanents.each do |x|
  if(!TimeHole.exists?(wigglerJson: x))
    TimeHole.create(permanent: true , wigglerJSON: x)
  end
end


